---
- hosts: all
  user: root
  become: yes
  tasks:
    - name: git installation
      yum:
        name: git
        state: present
    - name: maven installation
      yum:
        name: maven
        state: present
