--- 
- hosts: all
  user: root
  become: yes
  tasks:
    - name: tomcat installation
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
        dest: /root/apache-tomcat.tar.gz
    - name: extract tomcat file
      ansible.builtin.unarchive:   
         src: /root/apache-tomcat.tar.gz
         dest: /root
         remote_src: yes
